version: "3.9"
services:
    backend:
        build: ./apps
        restart: always
        ports:
            - "3000"
        volumes:
            - app-data:/app/public/images
volumes:
    app-data:
